const layerText={
Identity:"Identity & access protects confidentiality by checking who the user is, limiting privileges and adding verification beyond a username.",
Monitoring:"Monitoring turns activity into evidence. Active controls can block or quarantine; passive controls observe and analyse.",
Vulnerability:"Vulnerability management finds weaknesses, prioritises risk, coordinates remediation and repeats continuously.",
Data:"Encryption, tokenisation, masking and quarantining protect the information itself in transit, at rest and during use.",
Endpoint:"Endpoint control decides which devices may connect, enforces patch and credential policy, and feeds device activity back into SIEM/TIP."
};
document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>document.getElementById('layerReadout').textContent=layerText[b.dataset.layer]);

const nav=[...document.querySelectorAll('.rail nav a')],sections=[...document.querySelectorAll('section[id]')];
addEventListener('scroll',()=>{const d=document.documentElement,max=d.scrollHeight-d.clientHeight;document.getElementById('progress').style.width=(max?d.scrollTop/max*100:0)+'%';let active='brief';sections.forEach(s=>{if(scrollY>=s.offsetTop-120)active=s.id});nav.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+active))});

const cia={mfa:[22,10,4],least:[18,18,2],audit:[4,28,4],backup:[2,4,40],trusted:[22,8,4]},selected=new Set();
document.querySelectorAll('[data-cia]').forEach(b=>b.onclick=()=>{const k=b.dataset.cia;b.classList.toggle('active');b.classList.contains('active')?selected.add(k):selected.delete(k);let c=28,i=28,a=28;selected.forEach(x=>{c+=cia[x][0];i+=cia[x][1];a+=cia[x][2]});c=Math.min(c,100);i=Math.min(i,100);a=Math.min(a,100);[['C',c],['I',i],['A',a]].forEach(([x,v])=>{document.getElementById('m'+x).style.setProperty('--v',v+'%');document.getElementById('m'+x+'v').textContent=v});document.getElementById('ciaAdvice').textContent=selected.size>=4?'Layered controls now reinforce all three CIA properties.':selected.size>=2?'The design is improving, but important gaps remain.':'A policy exists, but the defensive stack is still thin.'});

document.querySelectorAll('[data-identity]').forEach(b=>b.onclick=()=>{const m={legit:'Legitimate use: the username and person match. Normal role and behaviour may be sufficient here.',stolen:'Credential theft: the username looks legitimate but the person is not. MFA, tokens or behavioural verification can expose the mismatch.',shared:'Credential sharing: the system still sees James. Strong policy plus MFA or individual verification is needed to prevent this ambiguity.'};document.getElementById('identityReadout').innerHTML='<p>'+m[b.dataset.identity]+'</p>'});

document.querySelectorAll('[data-monitor]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-monitor]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const active=b.dataset.monitor==='active';document.getElementById('monitorFlow').innerHTML=active?'<div class="node">Traffic source</div><div class="arrow">→</div><div class="node">R/W security element</div><div class="arrow">→</div><div class="node">Repository</div><div class="arrow">→</div><div class="node">Analytics</div>':'<div class="node">Traffic source</div><div class="arrow">↘</div><div class="node">Agent / probe</div><div class="arrow">→</div><div class="node">Repository</div><div class="arrow">→</div><div class="node">Analytics</div>';document.getElementById('monitorExplain').textContent=active?'Active monitoring sits directly in the network and can block, discard or quarantine traffic. Firewalls, IDS/IPS and active probes are examples used for real-time policy enforcement.':'Passive monitoring receives a copy or split of traffic. It can capture and analyse, but it does not directly influence the live data flow.'});

const traffic=document.getElementById('traffic');for(let i=0;i<34;i++){const e=document.createElement('i');e.style.height=(18+Math.random()*55)+'px';traffic.appendChild(e)}
document.getElementById('trafficSpike').onclick=()=>{[...traffic.children].forEach((e,i)=>{const hot=i>22&&i<29;e.style.height=(hot?120+Math.random()*50:18+Math.random()*55)+'px';e.classList.toggle('alert',hot)});document.getElementById('trafficText').textContent='Traffic has jumped sharply above the established pattern. Monitoring should alert, correlate context and decide whether containment is needed.'};

document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-method]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t={black:'Black box: the tester starts with no internal information and behaves like an outside adversary, often using OSINT against public-facing assets.',gray:'Gray box: the tester receives limited information, then discovers the rest. It sits between realism and broad coverage.',white:'White box: the tester receives complete system information, greatly reducing the chance that components are missed.'};document.getElementById('methodReadout').innerHTML='<p><b>'+t[b.dataset.method].split(':')[0]+':</b>'+t[b.dataset.method].split(':').slice(1).join(':')+'</p>'});

const cvIds=['cv1','cv2','cv3','cv4','cv5'];
function cvUpdate(){const vals=cvIds.map(id=>+document.getElementById(id).value);cvIds.forEach((id,i)=>document.getElementById(id+'v').textContent=vals[i]);const raw=(vals[0]*.18+vals[1]*.18+vals[2]*.16+vals[3]*.13+vals[4]*.35)/10;const score=Math.max(0,Math.min(10,raw));document.getElementById('cvScore').textContent=score.toFixed(1);const r=document.getElementById('cvRating'),a=document.getElementById('cvAdvice');let cls='low',txt='LOW',ad='Track and remediate through normal processes.';if(score>=9){cls='critical';txt='CRITICAL';ad='Immediate action: prioritise before routine work.'}else if(score>=7){cls='high';txt='HIGH';ad='Expedite remediation ahead of routine work.'}else if(score>=4){cls='medium';txt='MEDIUM';ad='Schedule remediation within normal patch cycles.'}r.className='rating '+cls;r.textContent=txt;a.textContent=ad}
cvIds.forEach(id=>document.getElementById(id).oninput=cvUpdate);cvUpdate();

const original='NAME: ALEX MORGAN<br>CARD: 5412 7788 9911 4207<br>SALARY: $148,000<br>ACCOUNT: AU-92217';
document.querySelectorAll('[data-protect]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-protect]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const box=document.getElementById('fakeData'),ex=document.getElementById('protectExplain');const mode=b.dataset.protect;if(mode==='encrypt'){box.innerHTML='CIPHERTEXT: 9F A1 73 C2 5E 0B 44 D8...';ex.innerHTML='<div class="badge blue">ENCRYPTION</div><h3>Make the data unreadable without the authorised key</h3><p>Use strong encryption for data in transit and at rest. Secure protocol equivalents such as HTTPS, FTPS and SSH protect movement across the network.</p>'}if(mode==='token'){box.innerHTML='NAME: ALEX MORGAN<br>CARD TOKEN: tok_7Q2-91X-Z44<br>SALARY: $148,000<br>ACCOUNT TOKEN: tok_AU_551';ex.innerHTML='<div class="badge blue">TOKENISATION</div><h3>Replace sensitive values with tokens</h3><p>The sensitive value stays protected in a token vault. The application can use the stand-in token without repeatedly exposing the original data.</p>'}if(mode==='mask'){box.innerHTML='NAME: ALEX M*****<br>CARD: 541 *** **** 207<br>SALARY: $***,***<br>ACCOUNT: AU-***17';ex.innerHTML='<div class="badge blue">MASKING</div><h3>Show only what the role needs</h3><p>Masking is least privilege applied to the data view. A stolen standard-user credential still encounters only the restricted representation.</p>'}if(mode==='quarantine'){box.innerHTML='ACCESS REQUEST: QUARANTINED<br>SESSION: BLOCKED<br>ACTIVITY: LOGGED<br>ALERT: SENT';ex.innerHTML='<div class="badge red">QUARANTINE</div><h3>Stop suspicious access before it continues</h3><p>Block the request, preserve the activity log and alert the relevant team. Network and endpoint controls can automate this response.</p>'}});

document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{const d=b.closest('.device'),m={ok:'Compliant endpoint: allow under policy, continue monitoring and patch enforcement.',review:'Review required: the device is personal and behind on patching. Restrict access until it meets policy.',block:'High-risk endpoint: jailbreaking bypasses OS restrictions. Block access to critical assets under the lecture policy.'};if(b.dataset.device==='block')d.classList.add('blocked');document.getElementById('deviceReadout').innerHTML='<p>'+m[b.dataset.device]+'</p>'});

document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>{const e=b.closest('.event'),m={identity:'Stronger third-party credential controls and MFA could reduce the chance that stolen credentials become valid access.',access:'Least privilege and tighter vendor access boundaries can limit what a third-party account is allowed to reach.',segment:'Network segmentation can constrain the pivot from a vendor-connected area into the broader corporate network.',endpoint:'Secure POS configuration, patching and point-to-point encryption can reduce endpoint exposure and payment-data capture.',monitor:'Monitoring feeding SIEM/TIP can shorten detection time by identifying abnormal access, malware or exfiltration patterns.'};e.classList.add('stopped');document.getElementById('breachReadout').innerHTML='<p><b>Intervention:</b> '+m[b.dataset.stop]+'</p>'});

document.querySelectorAll('.check').forEach(cp=>{const ans=+cp.dataset.answer,bs=[...cp.querySelectorAll('button')];bs.forEach((b,i)=>b.onclick=()=>{if(cp.dataset.done)return;cp.dataset.done='1';bs.forEach(x=>x.disabled=true);if(i===ans){b.classList.add('correct');cp.querySelector('.feedback').textContent='Correct.'}else{b.classList.add('wrong');bs[ans].classList.add('correct');cp.querySelector('.feedback').textContent='Not quite — compare the choice with the lecture definition.'}})});