const stageText={
cred:"Credential theft attacks identity first. Strong MFA, third-party access control and credential policy can reduce the chance that a stolen username/password becomes valid access.",
pivot:"Network movement tests segmentation and least privilege. A compromised account should not automatically reach the rest of the enterprise.",
malware:"Endpoint compromise tests patching, endpoint policy, configuration and data protection close to the device.",
exfil:"Exfiltration tests monitoring, encryption, tokenisation, masking and the organisation's ability to detect abnormal data movement."
};
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-stage]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('stageReadout').textContent=stageText[b.dataset.stage]});

const nav=[...document.querySelectorAll('.mast nav a')],secs=[...document.querySelectorAll('section[id]')];
addEventListener('scroll',()=>{const d=document.documentElement,max=d.scrollHeight-d.clientHeight;document.getElementById('progress').style.width=(max?d.scrollTop/max*100:0)+'%';let active='mission';secs.forEach(s=>{if(scrollY>=s.offsetTop-100)active=s.id});nav.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+active))});

const effects={mfa:[26,8,2],least:[20,20,2],audit:[3,32,3],backup:[2,4,45],trusted:[22,10,3]}, chosen=new Set();
document.querySelectorAll('[data-cia]').forEach(b=>b.onclick=()=>{const k=b.dataset.cia;b.classList.toggle('on');b.classList.contains('on')?chosen.add(k):chosen.delete(k);let c=25,i=25,a=25;chosen.forEach(x=>{c+=effects[x][0];i+=effects[x][1];a+=effects[x][2]});c=Math.min(100,c);i=Math.min(100,i);a=Math.min(100,a);[['C',c],['I',i],['A',a]].forEach(([k,v])=>{document.getElementById('bar'+k).style.setProperty('--v',v+'%');document.getElementById('val'+k).textContent=v});document.getElementById('ciaText').textContent=chosen.size>=4?'The stack is now layered: identity, authorisation, integrity checks and resilience overlap.':chosen.size>=2?'Better, but the design still has visible gaps.':'Baseline only. The environment still relies too heavily on trust.'});

document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{const t={james:'James: legitimate activity. The system sees james_analyst and the person is genuinely James.',john:'John: stolen credentials. The system can still log james_analyst unless another verification layer detects the mismatch.',molly:'Molly: shared credentials. Again, the system can log james_analyst even though another person is using the account.'};document.getElementById('identityAnswer').textContent=t[b.dataset.person]});

document.querySelectorAll('[data-monitor]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-monitor]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const active=b.dataset.monitor==='active';document.getElementById('flow').innerHTML=active?'<div class="node">Traffic source</div><span class="arrow">→</span><div class="node">R/W security element</div><span class="arrow">→</span><div class="node">Repository</div><span class="arrow">→</span><div class="node">Analytics</div>':'<div class="node">Traffic source</div><span class="arrow">↘</span><div class="node">Agent / probe</div><span class="arrow">→</span><div class="node">Repository</div><span class="arrow">→</span><div class="node">Analytics</div>';document.getElementById('monitorText').textContent=active?'Active monitoring sits in the network with read/write capability. It can block, discard or quarantine traffic.':'Passive monitoring observes a copy of traffic. It captures and analyses but cannot directly change the live flow.'});

const scope=document.getElementById('scope');for(let i=0;i<34;i++){const x=document.createElement('i');x.style.height=(18+Math.random()*55)+'px';scope.appendChild(x)}
function baseline(){[...scope.children].forEach(x=>{x.style.height=(18+Math.random()*55)+'px';x.classList.remove('hot')});document.getElementById('scopeText').textContent='The bars represent a stable traffic baseline.'}
document.getElementById('spike').onclick=()=>{[...scope.children].forEach((x,i)=>{const hot=i>21&&i<29;x.style.height=(hot?125+Math.random()*55:18+Math.random()*55)+'px';x.classList.toggle('hot',hot)});document.getElementById('scopeText').textContent='A sudden traffic spike has moved beyond the baseline. The monitoring system should alert, correlate context and support containment.'};
document.getElementById('normalise').onclick=baseline;

const ids=['s1','s2','s3','s4','s5'];
function risk(){const v=ids.map(id=>+document.getElementById(id).value);ids.forEach((id,i)=>document.getElementById(id+'v').textContent=v[i]);const n=(v[0]*.18+v[1]*.18+v[2]*.16+v[3]*.13+v[4]*.35)/10;const s=Math.max(0,Math.min(10,n));document.getElementById('riskN').textContent=s.toFixed(1);let band='LOW',txt='Track and remediate through routine processes.';if(s>=9){band='CRITICAL';txt='Immediate action: prioritise before routine work.'}else if(s>=7){band='HIGH';txt='Expedite remediation ahead of routine work.'}else if(s>=4){band='MEDIUM';txt='Schedule remediation within normal patch cycles.'}document.getElementById('riskBand').textContent=band;document.getElementById('riskText').textContent=txt}
ids.forEach(id=>document.getElementById(id).oninput=risk);risk();

document.querySelectorAll('[data-protect]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-protect]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const r=document.getElementById('record'),n=document.getElementById('protectNote'),m=b.dataset.protect;if(m==='encrypt'){r.textContent='CIPHERTEXT: 9F A1 73 C2 5E 0B 44 D8 ...';n.innerHTML='<div class="strip"><b>ENCRYPTION</b><p>Reversible cryptographic protection when an authorised key is available. The lecture applies encryption to both data in transit and data at rest.</p></div>'}if(m==='token'){r.textContent='NAME: ALEX MORGAN\nCARD TOKEN: tok_7Q2-91X-Z44\nSALARY: $148,000\nACCOUNT TOKEN: tok_AU_551';n.innerHTML='<div class="strip"><b>TOKENISATION</b><p>The sensitive value is replaced by a random token. The original remains protected in the token vault instead of travelling through every workflow.</p></div>'}if(m==='mask'){r.textContent='NAME: ALEX M*****\nCARD: 541 *** **** 207\nSALARY: $***,***\nACCOUNT: AU-***17';n.innerHTML='<div class="strip"><b>MASKING</b><p>Only the portion required by the role is visible. This limits exposure even after a user has authenticated.</p></div>'}if(m==='quarantine'){r.textContent='REQUEST: QUARANTINED\nSESSION: BLOCKED\nACTIVITY: LOGGED\nALERT: SENT';n.innerHTML='<div class="strip"><b>QUARANTINE</b><p>Suspicious access is stopped, logged and escalated rather than allowed to continue.</p></div>'}});

document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{const d=b.closest('.device'),m={allow:'Compliant or managed endpoint: allow according to policy, then continue monitoring and patch enforcement.',review:'Review required: a personal device with outdated patching should receive restricted access until it meets policy.',block:'Block: a jailbroken device bypasses operating-system restrictions and represents elevated risk.'};if(b.dataset.device==='block')d.classList.add('block');document.getElementById('deviceNote').textContent=m[b.dataset.device]});

document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>{const step=b.closest('.step'),m={mfa:'Insert stronger third-party credential controls and MFA before stolen credentials can be reused.',least:'Apply least privilege and tighter vendor access boundaries so a third-party account cannot reach unnecessary systems.',segment:'Use network segmentation to constrain movement from a vendor-connected zone into the wider corporate network.',endpoint:'Harden and patch POS endpoints; point-to-point encryption can reduce payment-data exposure on the terminal.',monitor:'Use monitoring feeding SIEM/TIP to identify abnormal malware or exfiltration activity earlier.'};step.classList.add('stopped');document.getElementById('replayNote').innerHTML='<b>CONTROL PLACED:</b> '+m[b.dataset.stop]});

document.querySelectorAll('.checkpoint').forEach(cp=>{const ans=+cp.dataset.answer,bs=[...cp.querySelectorAll('button')];bs.forEach((b,i)=>b.onclick=()=>{if(cp.dataset.done)return;cp.dataset.done='1';bs.forEach(x=>x.disabled=true);if(i===ans){b.classList.add('correct');cp.querySelector('.feedback').textContent='Correct.'}else{b.classList.add('wrong');bs[ans].classList.add('correct');cp.querySelector('.feedback').textContent='Not quite — compare it with the lecture definition and example.'}})});